# This file is part of the Stomper project.
#
# Licensed under the BSD 3-Clause License (the "License"); a copy of the License
# is included with this project. You may also obtain a copy of the License at:
#
#     https://opensource.org/licenses/BSD-3-Clause
#
# Additional licenses for third-party dependencies are also included
# and must be reviewed separately.

site_name: Stomper
site_url: https://www.stomper.cloud/
site_author: JoseLuisHD
repo_url: https://github.com/JoseLuisHD/Stomper
copyright: Copyright &copy; Stomper by JoseLuisHD

plugins:
  - search
  - tags
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: es
          name: Español
          build: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  language: en
  favicon: assets/stomper.ico
  logo: assets/stomper.webp
  features:
    - search.suggest
    - search.share
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.path
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JoseLuisHD/Stomper
    - icon: fontawesome/brands/discord
      link: https://discord.stomper.cloud

nav:
  - Home: index.md
